name: mathics-threejs-backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Puppeteer dependencies if testing locally
        if: ${{ env.ACT }}
        run: |
          sudo apt update
          sudo apt install libnss3-dev libgdk-pixbuf2.0-dev libgtk-3-dev libxss-dev libasound2 -y

      - name: Install dependencies
        run: npm install

      - name: Run the tests
        run: npm test
