name: mathics-threejs-backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        # express is already isntalled
        run: npm install backstopjs

      - name: Run the tests
        run: npm test
