name: mathics-threejs-backend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Install dependencies
        run: npm install -g backstopjs http-server

      - name: Start the local server
        run: http-server &

      - name: Run the tests
        run: backstop test

      - name: Stop the local server
        run: exit 0
